<?xml version="1.0"?>
<wsdl:definitions targetNamespace="http://www.herongyang.com/Service/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:hy="http://www.herongyang.com/Service/"
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
>
<wsdl:documentation>GetStockPrice_WSDL_11_SOAP_11_RPC.wsdl Copyright (c) herongyang.com. All rights reserved</wsdl:documentation>
<wsdl:message name="getStockPriceInputMessage">
<wsdl:part name="datePart" type="xsd:date" />
<wsdl:part name="stockPart" type="xsd:string" />
<wsdl:part name="marketPart" type="xsd:string" />
</wsdl:message>
<wsdl:message name="getStockPriceOutputMessage">
<wsdl:part name="pricePart" type="xsd:decimal" />
</wsdl:message>
<wsdl:portType name="getStockPricePortType">
<wsdl:operation name="GetStockPrice">
<wsdl:input name="getStockPriceInput" message="hy:getStockPriceInputMessage" />
<wsdl:output name="getStockPriceOutput" message="hy:getStockPriceOutputMessage" />
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="getStockPriceBinding" type="hy:getStockPricePortType">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
<wsdl:operation name="GetStockPrice">
<soap:operation style="rpc" soapAction="http://www.herongyang.com/Service/getStockPrice" />
<wsdl:input name="getStockPriceInput">
<soap:body use="encoded" parts="stockPart marketPart datePart" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
</wsdl:input>
<wsdl:output name="getStockPriceOutput">
<soap:body use="encoded" parts="pricePart" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="getStockPriceService">
<wsdl:port name="getStockPricePort" binding="hy:getStockPriceBinding">
<soap:address location="http://www.herongyang.com/Service/GetStockPrice.php" />
</wsdl:port>
</wsdl:service>
</wsdl:definitions>